on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Tencent Cloudbase Github Action Example
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Tencent CloudBase
        uses: TencentCloudBase/cloudbase-action@v2.0.1
        with: 
            # 云开发的访问密钥 secretId 和 secretKey
            secretId: ${{ secrets.SECRET_ID }}
            secretKey: ${{ secrets.SECRET_KEY }}
            # 云开发的环境id
            envId: ${{ secrets.ENV_ID }}
            # Github 项目静态文件的路径
            staticSrcPath: public
            staticDestPath: ./public

